export const date = Date.now();

export const BASICCOMISION = {
  fechaFin: {},
  nombreCurso: '',
  diaDeClases: '',
  precioComision: '',
  precioComisionDto: '',
  fechaInicio: {},
  horarioClase: '',
  duracionSemanas: '',
  mpLink: '',
  mpLinkDto: '',
};

export const COMISIONESFIELDS = [
  {
    nombre: 'nombreCurso',
    inputLabel: 'Curso',
    isRequired: true,
    type: 'select',
    id: 1,
    nroOrden: 1,
    width: '45%',
  },
  {
    nombre: 'diaDeClases',
    inputLabel: 'Dias de clases',
    isRequired: true,
    type: 'text',
    id: 2,
    nroOrden: 2,
    width: '45%',
  },
  {
    nombre: 'horarioClase',
    inputLabel: 'Horarios de clase',
    isRequired: false,
    type: 'text',
    id: 3,
    nroOrden: 3,
    width: '45%',
  },
  {
    nombre: 'duracionSemanas',
    inputLabel: 'Duracion en semanas',
    isRequired: true,
    type: 'text',
    id: 4,
    nroOrden: 4,
    width: '45%',
  },
  {
    nombre: 'fechaInicio',
    inputLabel: 'Fecha de Inicio',
    isRequired: true,
    type: 'date',
    id: 5,
    nroOrden: 5,
    width: '45%',
  },
  {
    nombre: 'fechaFin',
    inputLabel: 'Fecha de fin',
    isRequired: false,
    type: 'date',
    id: 6,
    nroOrden: 6,
    width: '45%',
  },
  {
    nombre: 'precioComision',
    inputLabel: 'Precio Total',
    isRelatedTo: 'precioComisionDto',
    isRequired: true,
    helpText: 'Agregar con decimales',
    type: 'number',
    id: 7,
    nroOrden: 7,
    width: '45%',
  },
  {
    nombre: 'precioComisionDto',
    inputLabel: 'Precio con 5% dto',
    isDisabled: true,
    helpText: 'Campo autogenerado',
    type: 'number',
    id: 8,
    nroOrden: 8,
    width: '45%',
  },
  {
    nombre: 'mpLink',
    inputLabel: 'Link de pago MP',
    isRequired: false,
    type: 'text',
    id: 9,
    nroOrden: 9,
    width: '45%',
  },
  {
    nombre: 'mpLinkDto',
    inputLabel: 'Link de pago MP c/dto',
    isRequired: false,
    type: 'text',
    id: 10,
    nroOrden: 10,
    width: '45%',
  },
];

export const COMISIONESROWS = [
  {
    nombre: 'Id',
    id: 1,
  },
  {
    nombre: 'Curso',
    inputLabel: 'Curso',
    isRequired: true,
    defaultValue: 'Online - En vivo',
    type: 'text',
    id: 6,
    nroOrden: 8,
    width: '45%',
  },
  {
    nombre: 'Fecha de Inicio',
    inputLabel: 'Fecha de Inicio',
    isRequired: true,
    type: 'text',
    id: 11,
    nroOrden: 2,
    width: '45%',
  },
  {
    nombre: 'Fecha de Fin',
    inputLabel: 'Fecha de Fin',
    isRequired: true,
    type: 'select',
    id: 3,
    nroOrden: 3,
    width: '45%',
  },

  {
    nombre: 'Editar/Ocultar',
    inputLabel: 'Programa de estudio',
    helpText: 'Este es un ejemplo autogenerado',
    type: 'text',
    id: 13,
    children: [],
    nroOrden: 15,
    width: '45%',
  },
];
