export const MPOPTIONS = [
  {
    name: true,
    id: 'true',
    label: 'Sí ',
    key: 'true',
    value: true,
  },
  {
    name: false,
    id: 'false',
    label: 'No ',
    key: 'false',
    value: false,
  },
];

export const BASICCURSO = {
  requisitos: 'Computadora y conexión a internet',
  modalidad: 'Online - En vivo',
  categoria: 'Programación',
  duracionClase: '',
  NroOrden: '',
  duracionTotal: '',
  planDeEstudioContent: [
    {
      contenido: '',
      orden: '',
      titulo: '',
    },
  ],
  isHidden: false,
  bannerImage: '',
  PDF: '',
  href: '',
  certificacion: 'Certificación Universitaria',
  descripcion: '',
  duracion: '',
  CategoriaID: '',
  precioInfo: '',
  clasesSemanales: '',
  nombre: '',
  aceptaMp: true,
};

export const CURSOSCFIELDS = [
  {
    nombre: 'NroOrden',
    inputLabel: 'Numero de orden',
    isRequired: false,
    type: 'number',
    id: 16,
    nroOrden: 0,
    width: '45%',
  },
  {
    nombre: 'bannerImage',
    inputLabel: 'Imagen Portada',
    helpText: 'Ingrese la url de la imagen',
    isRequired: true,
    type: 'textFile',
    id: 15,
    nroOrden: 1,
    width: '45%',
  },
  {
    nombre: 'nombre',
    inputLabel: 'Nombre del Curso',
    isRequired: true,
    isRelatedTo: 'href',
    type: 'text',
    id: 11,
    nroOrden: 2,
    width: '45%',
  },
  {
    nombre: 'categoria',
    inputLabel: 'Nombre de categoria',
    isRequired: true,
    isRelatedTo: 'CategoriaID',
    type: 'select',
    id: 3,
    nroOrden: 3,
    width: '45%',
  },
  {
    nombre: 'href',
    inputLabel: 'URL del curso',
    isDisabled: true,
    helpText: 'Campo autogenerado',
    type: 'text',
    id: 10,
    nroOrden: 4,
    width: '45%',
  },
  {
    nombre: 'CategoriaID',
    inputLabel: 'Categoria Id',
    isDisabled: true,
    helpText: 'Campo autogenerado',
    type: 'text',
    id: 1,
    nroOrden: 5,
    width: '45%',
  },

  {
    nombre: 'descripcion',
    inputLabel: 'Descripcion',
    isRequired: true,
    helpText: 'Ingrese la descripcion del curso',
    type: 'textarea',
    id: 4,
    nroOrden: 6,
    width: '100%',
  },
  {
    nombre: 'duracion',
    inputLabel: 'Duracion del curso en semanas',
    isRequired: true,
    type: 'text',
    id: 5,
    nroOrden: 7,
    width: '45%',
  },
  {
    nombre: 'modalidad',
    inputLabel: 'Modalidad del curso',
    type: 'text',
    id: 6,
    nroOrden: 8,
    width: '45%',
  },
  {
    nombre: 'certificacion',
    inputLabel: 'Tipo de certificacion',
    type: 'text',
    id: 6,
    nroOrden: 9,
    width: '45%',
  },
  {
    nombre: 'requisitos',
    inputLabel: 'Requisitos',
    type: 'text',
    id: 7,
    nroOrden: 10,
    width: '45%',
  },
  {
    nombre: 'clasesSemanales',
    inputLabel: 'Cantidad de clases semanales',
    isRequired: true,
    type: 'text',
    id: 8,
    nroOrden: 11,
    width: '45%',
  },
  {
    nombre: 'duracionClase',
    inputLabel: 'Duracion de cada clase',
    isRequired: true,
    type: 'text',
    id: 9,
    nroOrden: 12,
    width: '45%',
  },
  {
    nombre: 'duracionTotal',
    inputLabel: 'Duracion total del curso en horas',
    isRequired: true,
    type: 'text',
    id: 10,
    nroOrden: 13,
    width: '45%',
  },

  {
    nombre: 'PDF',
    inputLabel: 'Plan de estudios PDF',
    helpText: 'Ingrese la url del PDF',
    type: 'text',
    id: 11,
    nroOrden: 14,
    width: '45%',
  },
  {
    nombre: 'aceptaMp',
    inputLabel: 'Pago a través de Mercado Pago',
    type: 'select',
    options: MPOPTIONS,
    id: 12,
    nroOrden: 15,
    width: '45%',
  },
  {
    nombre: 'planDeEstudioContent',
    inputLabel: 'Programa de estudio',
    helpText: 'Complete con el titulo y contenido de cada parrafo',
    type: 'titleContent',
    id: 13,
    nroOrden: 16,
    width: '95%',
  },
];

export const CURSOSROWS = [
  {
    nombre: 'Id',
  },
  {
    nombre: 'Nombre Curso',
    inputLabel: 'Nombre del Curso',
    isRequired: true,
    type: 'text',
    id: 11,
    nroOrden: 2,
    width: '45%',
  },
  {
    nombre: 'Categoria',
    inputLabel: 'Nombre de categoria',
    isRequired: true,
    type: 'select',
    id: 3,
    nroOrden: 3,
    width: '45%',
  },

  {
    nombre: 'Modalidad',
    inputLabel: 'Modalidad del curso',
    defaultValue: BASICCURSO.modalidad,
    type: 'text',
    id: 6,
    nroOrden: 8,
    width: '45%',
  },

  {
    nombre: 'Editar/Ocultar',
    inputLabel: 'Programa de estudio',
    helpText: 'Este es un ejemplo autogenerado',
    type: 'text',
    id: 13,
    children: [],
    nroOrden: 15,
    width: '45%',
  },
];
